The notebook:  C:\Users\Conrad\Documents\GitHub\Projects\Python\NP-Array Shapes.ipynb

In [1]:
L1 = [0., 0.5, 1., 1.5, 2., 2.5]
L2 = [[0.],[0.5],[1.],[1.5],[2.],[2.5]]

In [2]:
print L1.index(1), L2.index([2.5])

2 5


In [3]:
L1.index(2.5)
L2.index([2.5])

5

In [4]:
import numpy as np

In [5]:
q = np.array([0., 0.5, 1.0, 1.5, 2., 2.5])
print 'The 1D list is: ', q, ' and its shape is ', q.shape

The 1D list is:  [ 0.   0.5  1.   1.5  2.   2.5]  and its shape is  (6L,)


In [6]:
q2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print 'The 2D list is: \n\n', q2, '\n\nand its shape is ', q2.shape

The 2D list is: 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

and its shape is  (3L, 3L)


In [7]:
q3 = (q2*q2)
print 'The product q2*q2 is a 2D list with element-by-element multiplication \n\n', q3, '\n\nand a shape of ', q3.shape

The product q2*q2 is a 2D list with element-by-element multiplication 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

and a shape of  (3L, 3L)


In [8]:
print 'There are many ways to sum an numpy array.\n'
q4_0 = q3.sum(axis=0)
print '\nCan sum the columns (i.e. across the rows), with sum(axis=0), to get a 1D row array\n', q4_0, '\nof shape', q4_0.shape
q4_1 = q3.sum(axis=1)
print '\nCan sum the row (i.e. across the columns), with sum(axis=1), to get a 1D row array\n', q4_1, '\nof shape', q4_1.shape
q4_s = q3.sum()
print '\nCan sum columns and rows to get 0D array\n', q4_s, '\nof shape', q4_s.shape

There are many ways to sum an numpy array.


Can sum the columns (i.e. across the rows), with sum(axis=0), to get a 1D row array
[ 66  93 126] 
of shape (3L,)

Can sum the row (i.e. across the columns), with sum(axis=1), to get a 1D row array
[ 14  77 194] 
of shape (3L,)

Can sum columns and rows to get 0D array
285 
of shape ()


In [9]:
q5_1 = q4_1.reshape(-1,1)
print 'The confusion comes between a list and a list-of-lists.  To see this reshape q4_1 using q4_1.reshape(-1,1) to get a 1D array\n', q5_1, '\nof shape', q5_1.shape
print '\nNote the extra "index"'

The confusion comes between a list and a list-of-lists.  To see this reshape q4_1 using q4_1.reshape(-1,1) to get a 1D array
[[ 14]
 [ 77]
 [194]] 
of shape (3L, 1L)

Note the extra "index"


In [10]:
q6_1 = q4_1 + q5_1
print 'So far the change looks cosmetic but look what happens when the 1D list-of-lists is added to the 1D list\n.'
print 'The result of q5_1 + q4_1 gives a 2D array\n',q6_1,'\nof shape', q6_1.shape
print '\nThe result is a sort of outer-sum'

So far the change looks cosmetic but look what happens when the 1D list-of-lists is added to the 1D list
.
The result of q5_1 + q4_1 gives a 2D array
[[ 28  91 208]
 [ 91 154 271]
 [208 271 388]] 
of shape (3L, 3L)

The result is a sort of outer-sum


In [11]:
scalar = 7
q7 = scalar + q4_s
print "This sort of coercion occurs even for the one element case."
print "An integer doesn't have a shape but add it to q4_s and the result does.\n"
print 'The result is: ', q7, 'with shape ', q7.shape

This sort of coercion occurs even for the one element case.
An integer doesn't have a shape but add it to q4_s and the result does.

The result is:  292 with shape  ()
